# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/YoisakiKnd"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/@anyakanade"

[social.params]
icon = "brand-twitter"


[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/185604274"

[social.params]
icon = "brand-bilibili"
